# copy right
# Licenses http://www.apache.org/licenses/LICENSE-2.0
# more info see https://docs.docker.com/compose/compose-file/ or https://docker.github.io/compose/compose-file/
version: '3.7'

networks:
  default:
#volumes:
#  web-data:
services:
  temp-go-cron:
    container_name: "${ROOT_NAME}"
    image: '${ROOT_NAME}:${DIST_TAG}' # see local docker file
    ports:
      - "39000:${ENV_CRON_PORT}"
    volumes:
      - "$PWD:/usr/src/myapp"
    environment:
      - ENV_CRON_HTTPS_ENABLE=false
      - ENV_CRON_AUTO_HOST=false
      - ENV_CRON_HOST=${ENV_CRON_HOST}:${ENV_CRON_PORT}
#      - ENV_CRON_HOST=0.0.0.0:39000
    working_dir: "/usr/src/myapp"
    command:
      - make
      - dev

