runmode: release             # run mode: debug, release, test
name: temp-go-cron           # name of App
addr: :39000                 # HTTP port will cover by use env: ENV_CRON_HOST

base_path: /v1                     # api version
prod_url: http://127.0.0.1:39000   # prod url full ip:port
test_url: http://127.0.0.1:39000   # test url full ip:port
dev_url: http://127.0.0.1:39000     # dev url full ip:port
sslEnable: false                    # isEnable ssl mode this will cover by env ENV_CRON_HTTPS_ENABLE

zap:
  AtomicLevel: 1 # DebugLevel:-1 InfoLevel:0 WarnLevel:1 ErrorLevel:2
  FieldsAuto: false # is use auto Fields key set
  Fields:
    Key: key
    Val: val
  Development: false # is open Open file and line number
  Encoding: console # output format, only use console or json, default is console
  rotate:
    Filename: log/go-cron.log # Log file path
    MaxSize: 128 # Maximum size of each log file, Unit: M
    MaxBackups: 30 # How many backups are saved in the log file
    MaxAge: 365 # How many days can the file be keep, Unit: day
    Compress: true # need compress
  EncoderConfig:
    TimeKey: time
    LevelKey: level
    NameKey: logger
    CallerKey: caller
    MessageKey: msg
    StacktraceKey: stacktrace

monitor: # monitor
  status: true             # api status use {monitor.health}
  health: /status/health   # api health
  retryCount: 10           # ping api health retry count
  hardware: false           # hardware true or false
  status_hardware:
    disk: /status/hardware/disk     # hardware api disk
    cpu: /status/hardware/cpu       # hardware api cpu
    ram: /status/hardware/ram       # hardware api ram
  debug: false                       # debug true or false
  pprof: false                       # security true or false
  security: true                    # debug and security security true or false
  securityUser:
    admin:  abcdefg # admin:pwd
